// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPdQ5zbFmLugYnw0-8BIU-y1YubhwYmv4',
    appId: '1:756150265167:web:43b970c8960b9724f3913a',
    messagingSenderId: '756150265167',
    projectId: 'capturalens-84b72',
    authDomain: 'capturalens-84b72.firebaseapp.com',
    storageBucket: 'captura-83119.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtPG5Y1mUZsLU1p5ON7yWRmtAPddzoXEI',
    appId: '1:756150265167:android:7947067b6cc3f6f6f3913a',
    messagingSenderId: '756150265167',
    projectId: 'capturalens-84b72',
    storageBucket: 'captura-83119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-pDlI-AqPZxNJr5b8_rP4IjGqnv6fEcc',
    appId: '1:756150265167:ios:a173c22e5457d9baf3913a',
    messagingSenderId: '756150265167',
    projectId: 'capturalens-84b72',
    storageBucket: 'captura-83119.appspot.com',
    iosBundleId: 'com.example.capturaLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-pDlI-AqPZxNJr5b8_rP4IjGqnv6fEcc',
    appId: '1:756150265167:ios:a173c22e5457d9baf3913a',
    messagingSenderId: '756150265167',
    projectId: 'capturalens-84b72',
    storageBucket: 'captura-83119.appspot.com',
    iosBundleId: 'com.example.capturaLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPdQ5zbFmLugYnw0-8BIU-y1YubhwYmv4',
    appId: '1:756150265167:web:cf459d8b702a00b6f3913a',
    messagingSenderId: '756150265167',
    projectId: 'capturalens-84b72',
    authDomain: 'capturalens-84b72.firebaseapp.com',
    storageBucket: 'captura-83119.appspot.com',
  );
}
